import 'dart:io';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'cad_controller.dart';
import 'cad_geometry.dart';
import 'cad_models.dart';
import 'cad_overlay.dart';
import 'cad_import_export.dart';
import 'tm3_inverse.dart';
import 'cad_workspace.dart';
import 'layer_manager.dart';

void main()=>runApp(const CepAraziApp());
class CepAraziApp extends StatelessWidget{const CepAraziApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'CepArazi',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF1565C0)),useMaterial3:true),home:const MapPage());}
class TmPoint{final double e,n;final int dom;const TmPoint(this.e,this.n,this.dom);}
TmPoint toTm3(double lat,double lon){final p=latLngToTm3(LatLng(lat,lon));return TmPoint(p.easting,p.northing,p.dom);}
class SavedPoint{final int no;final DateTime time;final Position pos;final TmPoint tm;SavedPoint(this.no,this.time,this.pos,this.tm);}
class MapPage extends StatefulWidget{const MapPage({super.key});@override State<MapPage> createState()=>_MapPageState();}
class _MapPageState extends State<MapPage>{
 Position? _pos;TmPoint? _tm;final List<SavedPoint> _points=[];final _eCtrl=TextEditingController();final _nCtrl=TextEditingController();
 final CadController _cad=CadController();late final CadWorkspace _workspace;bool _busy=false;MapType _mapType=MapType.satellite;GoogleMapController? _map;
 @override void initState(){super.initState();_workspace=CadWorkspace(cad:_cad);_cad.addListener(_changed);_workspace.addListener(_changed);_locate();}
 @override void dispose(){_cad.removeListener(_changed);_workspace.removeListener(_changed);_workspace.dispose();_cad.dispose();_eCtrl.dispose();_nCtrl.dispose();super.dispose();}
 void _changed(){if(mounted)setState((){});}
 void _syncSnap(){_cad.setExternalSnapPoints([..._points.map((x)=>LatLng(x.pos.latitude,x.pos.longitude)),..._workspace.layers.snapPoints()]);}
 Future<void> _locate()async{setState(()=>_busy=true);try{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever)throw Exception('Konum izni gerekli');if(!await Geolocator.isLocationServiceEnabled())throw Exception('Telefon konum servisini ac');final pos=await Geolocator.getCurrentPosition(locationSettings:const LocationSettings(accuracy:LocationAccuracy.best,timeLimit:Duration(seconds:20)));final tm=toTm3(pos.latitude,pos.longitude);setState((){_pos=pos;_tm=tm;});_map?.animateCamera(CameraUpdate.newLatLngZoom(LatLng(pos.latitude,pos.longitude),19));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>_busy=false);}}
 void _savePoint(){if(_pos==null||_tm==null)return;setState(()=>_points.add(SavedPoint(_points.length+1,DateTime.now(),_pos!,_tm!)));_syncSnap();}
 void _start(CadDrawMode m){_cad.setMode(m);Navigator.of(context).maybePop();}
 Future<void> _shareTextFile(String name,String text,String mime)async{try{final dir=await getTemporaryDirectory();final f=File('${dir.path}/$name');await f.writeAsString(text,flush:true);await Share.shareXFiles([XFile(f.path,mimeType:mime)],subject:name);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Disa aktarma hatasi: $e')));}}
 Future<void> _exportKml()async{final v=_cad.state.vertices;if(v.length<2)return;await _shareTextFile('ceparazi.${_cad.state.mode==CadDrawMode.polygon?'polygon':'line'}.kml',exportKml(v,closed:_cad.state.mode==CadDrawMode.polygon),'application/vnd.google-earth.kml+xml');}
 Future<void> _exportDxf()async{final v=_cad.state.vertices;if(v.length<2)return;final dom=latLngToTm3(v.first).dom;await _shareTextFile('ceparazi_tm3_dom$dom.dxf',exportDxf(v,closed:_cad.state.mode==CadDrawMode.polygon,forcedDom:dom),'application/dxf');}
 Future<void> _importFile()async{try{final layer=await _workspace.importFile(dxfDom:_tm?.dom??33);if(layer==null)return;_syncSnap();final c=_workspace.centerOf(layer);if(c!=null)await _map?.animateCamera(CameraUpdate.newLatLngZoom(c,19));if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('${layer.source} katmani yuklendi • ${layer.vertices.length} kose')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Dosya acma hatasi: $e')));}}
 void _showLayers()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(ctx)=>LayerSheet(manager:_workspace.layers,onZoom:(layer){final c=_workspace.centerOf(layer);Navigator.pop(ctx);if(c!=null)_map?.animateCamera(CameraUpdate.newLatLngZoom(c,19));}));
 void _commitCurrent(){if(_cad.state.vertices.length<2)return;_workspace.commitCurrent();_syncSnap();ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Cizim katmana eklendi')));}
 void _addCoordinate(){final e=double.tryParse(_eCtrl.text.replaceAll(',','.')),n=double.tryParse(_nCtrl.text.replaceAll(',','.'));if(e==null||n==null)return;final dom=_tm?.dom??33;if(_cad.state.mode==CadDrawMode.none)_cad.setMode(CadDrawMode.polyline);_cad.addExactVertex(tm3ToLatLng(e,n,dom));Navigator.pop(context);}
 void _coordinateDialog()=>showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(ctx)=>Padding(padding:EdgeInsets.fromLTRB(20,4,20,MediaQuery.of(ctx).viewInsets.bottom+24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Koordinatla Kose • DOM ${_tm?.dom??33}°',style:Theme.of(ctx).textTheme.titleLarge),const SizedBox(height:12),TextField(controller:_eCtrl,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Y / Dogu',border:OutlineInputBorder())),const SizedBox(height:8),TextField(controller:_nCtrl,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'X / Kuzey',border:OutlineInputBorder())),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:_addCoordinate,child:const Text('Kose Ekle')))])));
 void _showTools()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(ctx)=>SafeArea(child:ListView(shrinkWrap:true,padding:const EdgeInsets.fromLTRB(10,0,10,20),children:[const ListTile(title:Text('CAD Araclari',style:TextStyle(fontWeight:FontWeight.bold))),ListTile(leading:const Icon(Icons.polyline),title:const Text('Cizgi'),onTap:()=>_start(CadDrawMode.polyline)),ListTile(leading:const Icon(Icons.pentagon_outlined),title:const Text('Poligon / Alan'),onTap:()=>_start(CadDrawMode.polygon)),ListTile(leading:const Icon(Icons.straighten),title:const Text('Mesafe / Azimut'),onTap:()=>_start(CadDrawMode.measure)),SwitchListTile(secondary:const Icon(Icons.control_point_duplicate),title:const Text('SNAP'),subtitle:Text('${_cad.state.snapToleranceMeters.toStringAsFixed(1)} m tolerans'),value:_cad.state.snapEnabled,onChanged:(v){_cad.setSnapEnabled(v);Navigator.pop(ctx);}),ListTile(leading:const Icon(Icons.add_box_outlined),title:const Text('Koordinatla Kose Ekle'),onTap:(){Navigator.pop(ctx);_coordinateDialog();}),ListTile(leading:const Icon(Icons.undo),title:const Text('Geri Al'),enabled:_cad.canUndo,onTap:(){_cad.undo();Navigator.pop(ctx);}),ListTile(leading:const Icon(Icons.redo),title:const Text('Yinele'),enabled:_cad.canRedo,onTap:(){_cad.redo();Navigator.pop(ctx);}),ListTile(leading:const Icon(Icons.save_alt),title:const Text('Cizimi Katmana Ekle'),enabled:_cad.state.vertices.length>=2,onTap:(){Navigator.pop(ctx);_commitCurrent();}),const Divider(),ListTile(leading:const Icon(Icons.file_open),title:const Text('DXF / KML Ice Aktar'),subtitle:Text('DXF icin DOM ${_tm?.dom??33}°'),onTap:(){Navigator.pop(ctx);_importFile();}),ListTile(leading:const Icon(Icons.layers),title:const Text('Katmanlar'),trailing:Badge(label:Text('${_workspace.layers.layers.length}')),onTap:(){Navigator.pop(ctx);_showLayers();}),const Divider(),ListTile(leading:const Icon(Icons.public),title:const Text('KML Disa Aktar'),enabled:_cad.state.vertices.length>=2,onTap:(){Navigator.pop(ctx);_exportKml();}),ListTile(leading:const Icon(Icons.architecture),title:const Text('DXF Disa Aktar'),enabled:_cad.state.vertices.length>=2,onTap:(){Navigator.pop(ctx);_exportDxf();})])));
 void _stakeout(){if(_tm==null)return;final te=double.tryParse(_eCtrl.text.replaceAll(',','.')),tn=double.tryParse(_nCtrl.text.replaceAll(',','.'));if(te==null||tn==null)return;final de=te-_tm!.e,dn=tn-_tm!.n,d=math.sqrt(de*de+dn*dn);var az=math.atan2(de,dn)*180/math.pi;if(az<0)az+=360;showModalBottomSheet(context:context,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Aplikasyon',style:Theme.of(context).textTheme.titleLarge),Text('Mesafe: ${d.toStringAsFixed(3)} m',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),Text('Azimut: ${az.toStringAsFixed(4)}°'),Text('Dogu: ${de.toStringAsFixed(3)} m  Kuzey: ${dn.toStringAsFixed(3)} m')])));}
 void _showStakeoutInput()=>showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(ctx)=>Padding(padding:EdgeInsets.fromLTRB(20,4,20,MediaQuery.of(ctx).viewInsets.bottom+24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Hedef Koordinat • DOM ${_tm?.dom}°',style:Theme.of(ctx).textTheme.titleLarge),const SizedBox(height:12),TextField(controller:_eCtrl,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Y / Dogu',border:OutlineInputBorder())),const SizedBox(height:8),TextField(controller:_nCtrl,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'X / Kuzey',border:OutlineInputBorder())),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){Navigator.pop(ctx);_stakeout();},child:const Text('Hesapla')))])));
 void _showPoints()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(ctx)=>ListView(shrinkWrap:true,children:[for(final x in _points.reversed)ListTile(leading:CircleAvatar(child:Text('${x.no}')),title:Text('Y ${x.tm.e.toStringAsFixed(3)} X ${x.tm.n.toStringAsFixed(3)}'),subtitle:Text('DOM ${x.tm.dom}° • ±${x.pos.accuracy.toStringAsFixed(2)} m'),onTap:(){Navigator.pop(ctx);_map?.animateCamera(CameraUpdate.newLatLngZoom(LatLng(x.pos.latitude,x.pos.longitude),20));})]));
 @override Widget build(BuildContext context){final p=_pos,tm=_tm,cadData=buildCadOverlay(_cad.state);final markers=<Marker>{for(final x in _points)Marker(markerId:MarkerId('p${x.no}'),position:LatLng(x.pos.latitude,x.pos.longitude),infoWindow:InfoWindow(title:'N${x.no}')),...cadData.markers};final lines=<Polyline>{..._workspace.layers.polylines(),...cadData.polylines};final polys=<Polygon>{..._workspace.layers.polygons(),...cadData.polygons};return Scaffold(appBar:AppBar(title:const Text('CepArazi'),actions:[IconButton(tooltip:'Katmanlar',onPressed:_showLayers,icon:Badge(isLabelVisible:_workspace.layers.layers.isNotEmpty,label:Text('${_workspace.layers.layers.length}'),child:const Icon(Icons.layers))),IconButton(tooltip:'CAD',onPressed:_showTools,icon:Badge(isLabelVisible:_cad.state.vertices.isNotEmpty,label:Text('${_cad.state.vertices.length}'),child:const Icon(Icons.architecture))),IconButton(onPressed:()=>setState(()=>_mapType=_mapType==MapType.satellite?MapType.hybrid:MapType.satellite),icon:const Icon(Icons.map_outlined)),IconButton(onPressed:_busy?null:_locate,icon:const Icon(Icons.my_location))]),body:Stack(children:[GoogleMap(initialCameraPosition:const CameraPosition(target:LatLng(38,33),zoom:6),mapType:_mapType,myLocationEnabled:p!=null,myLocationButtonEnabled:false,compassEnabled:true,zoomControlsEnabled:false,markers:markers,polylines:lines,polygons:polys,onTap:_cad.addVertex,onMapCreated:(c){_map=c;if(p!=null)c.animateCamera(CameraUpdate.newLatLngZoom(LatLng(p.latitude,p.longitude),19));}),if(_cad.state.mode!=CadDrawMode.none)Positioned(left:10,right:10,top:10,child:CadMeasurementCard(state:_cad.state,data:cadData,onUndo:_cad.canUndo?_cad.undo:null,onRedo:_cad.canRedo?_cad.redo:null,onFinish:_cad.finish)),if(_cad.state.mode==CadDrawMode.none)Positioned(left:10,right:10,top:10,child:Card(child:Padding(padding:const EdgeInsets.all(12),child:tm==null?Text(_busy?'GNSS konumu aliniyor…':'Konum bekleniyor'):Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.gps_fixed,size:18),const SizedBox(width:6),Text('ITRF / GRS80 TM3 DOM ${tm.dom}°',style:const TextStyle(fontWeight:FontWeight.bold)),const Spacer(),Text('±${p!.accuracy.toStringAsFixed(1)} m')]),Text('Y: ${tm.e.toStringAsFixed(3)} m   X: ${tm.n.toStringAsFixed(3)} m')])))),Positioned(left:10,right:10,bottom:14,child:Card(child:Padding(padding:const EdgeInsets.all(8),child:Row(children:[Expanded(child:FilledButton.icon(onPressed:p==null?null:_savePoint,icon:const Icon(Icons.add_location_alt_outlined),label:const Text('Nokta Al'))),const SizedBox(width:6),Expanded(child:FilledButton.tonalIcon(onPressed:tm==null?null:_showStakeoutInput,icon:const Icon(Icons.navigation_outlined),label:const Text('Aplikasyon'))),IconButton(onPressed:_points.isEmpty?null:_showPoints,icon:Badge(label:Text('${_points.length}'),child:const Icon(Icons.list_alt))) ]))))]));}
}
